name: Release Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  semantic-versioning:
    name: Semantic Versioning
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}
      changelog: ${{ steps.versioning.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate Version and Changelog
        id: versioning
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          fallback-version: '2.0.0'
          skip-version-file: 'true'
          skip-commit: 'false'

  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: semantic-versioning
    if: needs.semantic-versioning.outputs.version != ''
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: |
          flutter build apk --release
          flutter build apk --split-per-abi --release

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-release-apks
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk

  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: semantic-versioning
    if: needs.semantic-versioning.outputs.version != ''
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: |
          flutter pub get
          cd ios && pod install && cd ..

      - name: Build iOS for Simulator
        run: flutter build ios --simulator --no-codesign

      - name: Create Unsigned IPA Package
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload
          zip -r NepPass.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-unsigned-build
          path: build/ios/iphoneos/NepPass.ipa

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [semantic-versioning, build-android, build-ios]
    if: needs.semantic-versioning.outputs.version != ''
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Android Artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-release-apks
          path: android-builds

      - name: Download iOS Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ios-unsigned-build
          path: ios-builds

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.semantic-versioning.outputs.version }}
          name: NepPass v${{ needs.semantic-versioning.outputs.version }}
          body: ${{ needs.semantic-versioning.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            android-builds/app-release.apk
            android-builds/app-armeabi-v7a-release.apk
            android-builds/app-arm64-v8a-release.apk
            android-builds/app-x86_64-release.apk
            ios-builds/NepPass.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}